### ISSUE TITLE
install web not current version

### ISSUE THREAD

**Issue by Arhell** [statiqdev/statiqdev.github.io#12]
https://statiq.dev/web/
Step 3: Install Statiq.Web

**Comment by daveaglick** [comment]
Good catch, thanks! There's a note under that:

> Use whatever is the most recent version of Statiq.Web. The --version flag is needed while the package is pre-release.

But given it looks like you missed that I probably need to make it clearer

**Comment by daveaglick** [comment]
Changed versions to `x.y.z` which will hopefully avoid mistaking the sample version for an actual one, thanks for pointing this out
